<?php

namespace Database\Seeders;

use App\Jobs\TranslateEventJob;
use App\Models\Events;
use App\Models\EventTranslations;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EventsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = [
        [
            'id' => 1,
            'user_id' => 1,
            'city_id' => 1,
            'title' => 'مؤتمر التكنولوجيا 2026',
            'description' => 'انضم إلينا في واحد من أكبر المؤتمرات التقنية في المنطقة، حيث يجتمع رواد الأعمال والمطورون والمستثمرون لمناقشة أحدث الاتجاهات في عالم التكنولوجيا. سيتضمن الحدث ورش عمل تفاعلية، جلسات نقاشية مع خبراء عالميين، وعروض تقديمية لأحدث المشاريع الناشئة. فرصة مثالية لتوسيع شبكة علاقاتك واكتساب معرفة عملية تساعدك في تطوير مستقبلك المهني.',
            'start_date' => '2026-04-02',
            'end_date' => '2026-04-02',
            'time' => '11:28',
            'image' => null,
            'langitude' => 31.295314257398246,
            'lattitude' => 30.080789254587074,
            'slug' => 'motmr-alabtkar-alteknology-2026',
            'is_active' => 1,
            'created_at' => '2026-04-02 09:28:59',
            'updated_at' => '2026-04-02 09:40:17',
            'deleted_at' => null,
            'sub_categorey_id' => 3,
            'is_historical' => 0,
        ],
        [
            'id' => 2,
            'user_id' => 1,
            'city_id' => 2,
            'title' => 'مهرجان الموسيقى الصيفي',
            'description' => 'استمتع بأجواء صيفية لا تُنسى في مهرجان يجمع بين أفضل الفرق الموسيقية المحلية والعالمية. يقدم الحدث مجموعة متنوعة من الأنماط الموسيقية التي تناسب جميع الأذواق، بالإضافة إلى مناطق ترفيهية، أكشاك طعام، وأنشطة ممتعة للعائلات. تجربة مليئة بالحماس والطاقة الإيجابية.',
            'start_date' => '2026-04-02',
            'end_date' => '2026-04-03',
            'time' => '11:30',
            'image' => null,
            'langitude' => 31.383162120798744,
            'lattitude' => 31.046886727866962,
            'slug' => 'mhrgan-almosyk-alsyfy-2026',
            'is_active' => 1,
            'created_at' => '2026-04-04 09:30:30',
            'updated_at' => '2026-04-02 11:54:32',
            'deleted_at' => null,
            'sub_categorey_id' => 4,
            'is_historical' => 0,
        ],
        [
            'id' => 3,
            'user_id' => 1,
            'city_id' => 3,
            'title' => 'ورشة تطوير تطبيقات الموبايل',
            'description' => 'إذا كنت مهتمًا بدخول عالم تطوير التطبيقات، فهذه الورشة مصممة خصيصًا لك. ستتعلم أساسيات البرمجة باستخدام أحدث الأدوات، وكيفية بناء تطبيق متكامل خطوة بخطوة. الورشة عملية بنسبة كبيرة، وتشمل مشاريع حقيقية تساعدك على بناء Portfolio قوي.',
            'start_date' => '2026-04-02',
            'end_date' => '2026-04-03',
            'time' => '11:31',
            'image' => null,
            'langitude' => 2.378069532474882,
            'lattitude' => 48.80861034625076,
            'slug' => 'wrsh-totyr-tbykat-almobyyl',
            'is_active' => 1,
            'created_at' => '2026-04-02 09:32:10',
            'updated_at' => '2026-04-02 09:39:44',
            'deleted_at' => null,
            'sub_categorey_id' => 10,
            'is_historical' => 0,
        ],
        [
            'id' => 4,
            'user_id' => 1,
            'city_id' => 4,
            'title' => 'معرض ريادة الأعمال',
            'description' => 'حدث يجمع أصحاب المشاريع الناشئة مع المستثمرين والمهتمين بعالم البيزنس. يمكنك عرض فكرتك، الحصول على تمويل، أو حتى التعرف على شركاء محتملين. يتضمن المعرض جلسات إرشادية، قصص نجاح، ونصائح عملية لبدء مشروعك الخاص بثقة.',
            'start_date' => '2026-04-02',
            'end_date' => '2026-04-04',
            'time' => '11:33',
            'image' => null,
            'langitude' => -76.94883201634252,
            'lattitude' => 38.92395895391661,
            'slug' => 'mard-ryad-alamal',
            'is_active' => 1,
            'created_at' => '2026-04-02 09:34:04',
            'updated_at' => '2026-04-02 09:40:03',
            'deleted_at' => null,
            'sub_categorey_id' => 7,
            'is_historical' => 0,
        ],
        [
            'id' => 5,
            'user_id' => 1,
            'city_id' => 5,
            'title' => 'لقاء استراتيجي',
            'description' => 'تعرف على أحدث استراتيجيات التسويق عبر الإنترنت من خلال خبراء في المجال. يغطي الحدث مواضيع مثل الإعلانات المدفوعة، تحسين محركات البحث، إدارة السوشيال ميديا، وبناء العلامة التجارية. مناسب لأصحاب المشاريع والمسوقين وكل من يريد زيادة حضوره الرقمي.',
            'start_date' => '2026-04-02',
            'end_date' => '2026-04-03',
            'time' => '11:35',
            'image' => null,
            'langitude' => 44.43577324219572,
            'lattitude' => 33.26248900302403,
            'slug' => 'lkaaa-astyratyjy',
            'is_active' => 1,
            'created_at' => '2026-04-02 09:35:17',
            'updated_at' => '2026-04-02 09:35:17',
            'deleted_at' => null,
            'sub_categorey_id' => 5,
            'is_historical' => 0,
        ],
        [
            'id' => 6,
            'user_id' => 1,
            'city_id' => 6,
            'title' => 'مؤتمر التعليم الرقمي',
            'description' => 'برنامج تدريبي مكثف يمتد لعدة أيام، يهدف إلى تعليم أساسيات البرمجة بطريقة مبسطة وعملية. لا يتطلب أي خبرة سابقة، حيث يبدأ من الصفر حتى تنفيذ مشاريع بسيطة. بيئة تعليمية مشجعة تساعدك على اكتشاف مهاراتك وتطويرها.',
            'start_date' => '2026-04-02',
            'end_date' => '2026-04-03',
            'time' => '11:36',
            'image' => null,
            'langitude' => -0.13003253506045098,
            'lattitude' => 51.493135162160456,
            'slug' => 'mowtmer-altalyem-alrkm',
            'is_active' => 1,
            'created_at' => '2026-04-04 09:36:41',
            'updated_at' => '2026-04-02 09:40:09',
            'deleted_at' => null,
            'sub_categorey_id' => 9,
            'is_historical' => 0,
        ],
        [
            'id' => 7,
            'user_id' => 1,
            'city_id' => 7,
            'title' => 'مهرجان الأكل العالمي',
            'description' => 'رحلة حول العالم من خلال المذاقات! يضم المهرجان مجموعة كبيرة من المطاعم التي تقدم أطباقًا من مختلف الثقافات. بالإضافة إلى عروض طبخ مباشرة، مسابقات، وتجارب تذوق مميزة. مناسب للعائلات ومحبي الطعام.',
            'start_date' => '2026-04-02',
            'end_date' => '2026-04-03',
            'time' => '11:37',
            'image' => null,
            'langitude' => -3.6759048129097778,
            'lattitude' => 40.39833727270667,
            'slug' => 'mhrjan-alakl-alaalmy',
            'is_active' => 1,
            'created_at' => '2026-04-02 09:37:42',
            'updated_at' => '2026-04-02 09:39:51',
            'deleted_at' => null,
            'sub_categorey_id' => 6,
            'is_historical' => 0,
        ],
        [
            'id' => 10,
            'user_id' => 1,
            'city_id' => 8,
            'title' => 'رحلة اكتشاف الذات: بداية جديدة نحو الأفضل',
            'description' => 'في عالم سريع مليان ضغوط وتحديات، أحيانًا بننسى نفسنا وسط الزحمة.',
            'start_date' => '2026-04-04',
            'end_date' => '2026-04-05',
            'time' => '09:51',
            'image' => null,
            'langitude' => -77.02908928427279,
            'lattitude' => 38.96073174947932,
            'slug' => 'rhl-aktshaf-althat-bday-gdyd-nho-alafdl-XzBPQ-1775',
            'is_active' => 1,
            'created_at' => '2026-04-04 07:51:30',
            'updated_at' => '2026-04-04 07:51:48',
            'deleted_at' => null,
            'sub_categorey_id' => 9,
            'is_historical' => 0,
        ],
        [
            'id' => 11,
            'user_id' => 1,
            'city_id' => 9,
            'title' => 'انطلاقة رواد الأعمال: من فكرة لمشروع ناجح',
            'description' => 'لو عندك فكرة مشروع وواقف مش عارف تبدأ منين، الحدث ده معمول علشان يحطك على أول الطريق الصح.
هنغطي كل اللي محتاجه علشان تحول فكرتك لبيزنس حقيقي، بداية من دراسة السوق، لحد التسويق وبناء البراند.',
            'start_date' => '2026-04-04',
            'end_date' => '2026-04-05',
            'time' => '09:54',
            'image' => null,
            'langitude' => 55.2962506840704,
            'lattitude' => 25.215644808179135,
            'slug' => 'antlak-road-alaaamal-mn-fkr-lmshroaa-nagh-xTesx',
            'is_active' => 1,
            'created_at' => '2026-04-04 07:54:44',
            'updated_at' => '2026-04-04 07:59:08',
            'deleted_at' => null,
            'sub_categorey_id' => 10,
            'is_historical' => 0,
        ],
        [
            'id' => 12,
            'user_id' => 1,
            'city_id' => 10,
            'title' => 'ليلة المزاج العالي: مزيكا، طاقة، وانبساط',
            'description' => 'استعد لليلة مختلفة تمامًا!
مزيج من المزيكا الحية، DJ، وإضاءة مبهرة هيخلوك تعيش تجربة مليانة طاقة وحماس من أول دقيقة لآخر لحظة.

الحدث بيجمع بين:

عروض DJ ومزيكا متنوعة
فقرات ترفيهية وتفاعلية
مساحة للرقص والانبساط مع أصحابك
أجواء شبابية مليانة طاقة إيجابية',
            'start_date' => '2026-04-05',
            'end_date' => '2026-04-06',
            'time' => '09:56',
            'image' => null,
            'langitude' => 121.53346531062294,
            'lattitude' => 31.139186688189938,
            'slug' => 'lyl-almzag-alaaaly-mzyka-tak-oanbsat-n33E6',
            'is_active' => 1,
            'created_at' => '2026-04-04 07:57:13',
            'updated_at' => '2026-04-04 07:58:47',
            'deleted_at' => null,
            'sub_categorey_id' => 4,
            'is_historical' => 0,
        ],
        [
            'id' => 13,
            'user_id' => 1,
            'city_id' => 11,
            'title' => 'ليالي موسكو الشتوية: سحر الثلج والأنوار',
            'description' => 'في قلب موسكو، حيث يلتقي التاريخ بالجمال الشتوي، ندعوك لتجربة فريدة وسط أجواء ساحرة من الثلوج والإضاءة الدافئة.',
            'start_date' => '2026-04-04',
            'end_date' => '2026-04-07',
            'time' => '09:58',
            'image' => null,
            'langitude' => 37.56894380265018,
            'lattitude' => 55.771648313885976,
            'slug' => 'lyaly-mosko-alshtoy-shr-althlg-oalanoar-sz6Q5',
            'is_active' => 1,
            'created_at' => '2026-04-04 07:58:37',
            'updated_at' => '2026-04-04 07:58:56',
            'deleted_at' => null,
            'sub_categorey_id' => 5,
            'is_historical' => 0,
        ],
        [
            'id' => 14,
            'user_id' => 1,
            'city_id' => 3,
            'title' => 'يوم الابتكار والإبداع',
            'description' => 'حدث مميز بيجمع بين العقول المبدعة والمهتمين بالتطوير والابتكار في مكان واحد.
هتتعرف على أفكار جديدة، وتجارب ملهمة، وأدوات حديثة تساعدك تطور مهاراتك وتحوّل أفكارك لمشاريع حقيقية.',
            'start_date' => '2026-04-04',
            'end_date' => '2026-04-05',
            'time' => '10:20',
            'image' => null,
            'langitude' => 31.370809818213928,
            'lattitude' => 31.0325176479937,
            'slug' => 'yom-alabtkar-oalabdaaa-EQroI',
            'is_active' => 1,
            'created_at' => '2026-04-04 08:21:22',
            'updated_at' => '2026-04-04 08:21:35',
            'deleted_at' => null,
            'sub_categorey_id' => 7,
            'is_historical' => 0,
        ],
        [
            'id' => 15,
            'user_id' => 1,
            'city_id' => 1,
            'title' => 'يوم الابتكار والإبداع',
            'description' => 'حدث مميز بيجمع بين العقول المبدعة والمهتمين بالتطوير والابتكار في مكان واحد.
هتتعرف على أفكار جديدة، وتجارب ملهمة، وأدوات حديثة تساعدك تطور مهاراتك وتحوّل أفكارك لمشاريع حقيقية.',
            'start_date' => '2026-04-04',
            'end_date' => '2026-04-05',
            'time' => '10:34',
            'image' => null,
            'langitude' => 46.7750917392263,
            'lattitude' => 24.692064946718034,
            'slug' => 'yom-alabtkar-oalabdaaa-B9BJz',
            'is_active' => 1,
            'created_at' => '2026-04-04 08:35:07',
            'updated_at' => '2026-04-04 08:35:42',
            'deleted_at' => null,
            'sub_categorey_id' => 5,
            'is_historical' => 0,
        ],
    ];

        foreach ($events as $event) {
            $event['slug'] = Str::slug($event['title']).'-'.Str::random(5).time();
            $event = Events::create($event);
            EventTranslations::create([
                'event_id' => $event->id,
                'title' => $event->title,
                'description' => $event->description,
                'locale' => 'ar',
            ]);
            TranslateEventJob::dispatch($event->id, $event->title, $event->description);
        }

    }
}
