version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - /var/www/node_modules
    networks:
      - laravel-network
    depends_on:
      - mysql
      - redis
    ports:
      - "8000:8000"
      - "5174:5174"

  mysql:
    image: mysql:8.0
    container_name: SceMory
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: SceMory-password
      MYSQL_DATABASE: SceMory-db
      MYSQL_USER: SceMory-user
      MYSQL_PASSWORD: SceMory-password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  redis:
    image: redis:7.0
    container_name: laravel-redis
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    environment:
      PMA_HOST: SceMory
      MYSQL_ROOT_PASSWORD: SceMory-password
    ports:
      - "8080:80"
    networks:
      - laravel-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-worker
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - /var/www/node_modules
    command: php artisan queue:work --sleep=3 --tries=3
    depends_on:
      - app
      - redis
      - mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
